### ISSUE TITLE
Photo captions are missing

### ISSUE THREAD

**Issue by TemeV** [Kaffeine/telegram-qt#14]
Captions for photos are empty in all the debug prints.

**Comment by Kaffeine** [comment]
Should be closed by a8833052d66b67d3fc3e2d32b1935fdc6d3c63ef, but I can't test it yet.

**Comment by Kaffeine** [comment]
Captions are empty for me too. Seems to be not included in server->client package at all. I though it is because of wrong API level, but we declare level 23, which is the right one.

**Comment by Kaffeine** [comment]
Ouh, current layer is 45. The documentation seems to be not updated after "official client" contest. There is a lot of undocumented methods and variables.
https://core.telegram.org/method/contacts.resolveUsername
https://core.telegram.org/method/account.changePhone and many many more. How disappointing..

**Comment by TemeV** [comment]
Oh, that's really disappointing. Where did you find info about layer 45? I can't find anything mentioned above 23. Would updating to 45 be possible? Libqtelegram guys seem to be on layer 29 https://github.com/Aseman-Land/libqtelegram-aseman-edition/blob/master/telegram/coretypes.h

**Comment by Kaffeine** [comment]
I looked at the official desktop client:
https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/mtpCoreTypes.h#L371

Also, I hoped to get at least new API scheme in bot API, but it's not in json or their usual text format: https://core.telegram.org/bots/api#message

It seems that they have much more flags: search for  "class MTPDmessage : public mtpDataImpl<MTPDmessage>" at file https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/SourceFiles/mtproto/mtpScheme.h (the file have more than 30000 lines and github refuses to show it in other than raw mode) and take a look to the flags enum. Compare it to documented flags: https://core.telegram.org/constructor/message#parameters.

**Comment by Kaffeine** [comment]
On layer 23 we have caption member in Photo [1] and Video [2],  but the official client on layer 45 and Libqtelegram on layer 29 have no caption in Photo [3] and Video [4], but got a caption in MediaMessage [5]. Exactly as I wanted to do (and did) in our library.

I think Telegram guys just updated server and didn't added a code for new to old layer message conversion. We need to bump the layer, but it would be really hard to do without correct scheme [6].

[1] https://core.telegram.org/constructor/photo
[2] https://core.telegram.org/constructor/video
[3] https://github.com/Aseman-Land/libqtelegram-aseman-edition/blob/master/telegram/types/photo.h
[4] https://github.com/Aseman-Land/libqtelegram-aseman-edition/blob/master/telegram/types/video.h
[5] https://github.com/Aseman-Land/libqtelegram-aseman-edition/blob/master/telegram/types/messagemedia.h#L45
[6] https://core.telegram.org/schema/json (official scheme, layer 23+ (have more, than documented for 23, but still have caption for photo and video apart)

**Comment by TemeV** [comment]
Really odd. And yeah, the official client seems to be quite big... Libqtelegram guys have the layer 45 schema https://github.com/Aseman-Land/libqtelegram-code-generator/tree/master/schemas but not in json format. Would that be helpful?

**Comment by Kaffeine** [comment]
Yeah, it is helpful.
Time ago, when Telegram only started to discontinue documentation updating, I had to switch from the text format to json, because the last one was been much more complete. It seems that we have to revive code generation from the text format.

It's a very interesting question — where did they get it? I found the same file in the sources of the yet another official telegram client: https://github.com/zhukov/webogram/blob/master/app/js/lib/schema.tl.txt

There is a lot of changes from 23 to 45 layer. I think it would be reasonable to update our layer step-by-step, so the nearest goal would be to make telegram-qt works on layer 29.

I just pushed (40640f1c6b58dc56e0da32a92197628fc05bb906) an initial (and incomplete) version of generator for text format / layer 29.

* It misses flags implementation.
* Some new symbols match C++ keywords (e.g. new member "public" and new type "true")

---
About flags:
Say, we have follow line in the spec:
`webPage#ca820ed7 flags:# id:long url:string display_url:string type:flags.0?string site_name:flags.1?string title:flags.2?string description:flags.3?string photo:flags.4?Photo embed_url:flags.5?string embed_type:flags.5?string embed_width:flags.6?int embed_height:flags.6?int duration:flags.7?int author:flags.8?string document:flags.9?Document = WebPage;`

The same, reformatted:
```
    webPage#ca820ed7
        flags:#
        id:long
        url:string
        display_url:string
        type:flags.0?string
        site_name:flags.1?string
        title:flags.2?string
        description:flags.3?string
        photo:flags.4?Photo
        embed_url:flags.5?string
        embed_type:flags.5?string
        embed_width:flags.6?int
        embed_height:flags.6?int
        duration:flags.7?int
        author:flags.8?string
        document:flags.9?Document
            = WebPage;
```
I think this means that:
- There is an int "flag" member
- if we have zero bit == true in the read flag, then we should read string member "type" after display_url member.
and so on.

I still have to check it and implement in the generator.

**Comment by TemeV** [comment]
That would be the most logical way to interpret that syntax, and I guess it is also correct. At least it is what libqtelegram does https://github.com/Aseman-Land/libqtelegram-aseman-edition/blob/master/telegram/types/webpage.cpp#L216

Maybe this is the source for the others https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/mtproto/scheme.tl

**Comment by Kaffeine** [comment]
I just made the project to compiles on layer29 and the good news is that caption now works as intended.
The bad thing is that the library port to layer 29 is not complete yet, so there is a lot of different issues ATM. I pushed my current code to layer29 branch (5efe87cc5b42a73171ccf9d2d003c90582b6d969).

**Comment by TemeV** [comment]
Nice, I'll see if I can help with porting to layer29. But at least the caption issue is solved, yay!
